name: Docker Image Build
on:
  # push:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          entrypoint: ./.x-cmd/build
