name: Sync All Git Hosting Service
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 11 * * *'

jobs:
  publisher:
    runs-on: ubuntu-latest
    env:
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      ___X_CMD_CODESORUCE_REPO: dev
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: xws sync || exit
