name: Sync All Git Hosting Service
# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '0 0-14 * * 1-6'
on: workflow_dispatch

jobs:
  publisher:
    runs-on: ubuntu-latest
    env:
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        timeout-minutes: 8
        with:
          code: xws sync || exit
